### ISSUE TITLE
Is there some way of not needing the USB stick and login everytime?

### ISSUE THREAD

**Issue by vaughnad** [andriy921/Simple-Twitch#4] opened 2015-06-12 19:46 UTC
Hi, I got the app working (nice job by the way), but i see there is two main issues i`ve noticed:
1. You need to login in to the LG Store, but the app dont tell you this.
   -In my case i dont know why, but i have joined with facebook, and LG do not allow me to create a login with the same email or to join acc or something like that, so every single time i had to enter my full email and password to login (using facebook), dont know if there is some way to remember email in the normal login way but the facebook one do no work =/
   -that been said. Is there some way of not needing the login or to ask for the login in the app?
2. The app only shows when the USB stick is in when it is turned on.
   -Is there some way of installing the app so the usb is not needed anymore? or just if you install it with the LG store?

Thanks

**Comment by ericblade-owo** [comment] 2015-06-12 21:16
I'm not aware of any way to install an app that is on USB to the device directly, but if the application were submitted and accepted at the store, then people would be able to install it that way.  Might want to post at developer.lge.com and let the developer relations people know how much independent developers could really use the ability to connect directly to the tv and work with their applications that way. 

No idea on the facebook/LG store login thing.

**Comment by astashko** [comment] 2015-06-12 21:54
Hi, friend.
1. That's the policy of LG. You need to be logged in to the tore to run apps from usb. I didn't know about the issues with facebook - looks like LG fucked up here. If you register using email, then there's no need to enter your credentials again. So it seems like the best solution for you would be to create new email, register using it, login once and forget about this issue.
2. There's no other ways to run apps except from the store and usb sticks. That's the policy of LG (and, actually, other TV manufacturer's). The app is far from being ready to be accepted by LG into store. And considering, that it might be required to have permission from Twitch to publish it and that I would not bother with design of an app, I doubt that app would be anytime published to store.

Both issues are related to LG so there is nothing I can help here. You'll face exactly the same issues when you'll try to install any other app that is not available from store.

**Comment by vaughnad** [comment] 2015-06-12 22:14
That's too bad. LG did a great job choosing webos, but the UI and usability they implemented are just crap =/

My greatest problem is that i have apps paid in my login =/

**Comment by ericblade-owo** [comment] 2015-06-12 23:14
I have no idea what it takes to get into the LG app store (i'm on the engineering side, not the app store side), but developers would probably find it really useful if there were a web-app that could re-direct to another page at will.  Then you could host your development app on a local web-server, and point that app there.  I have no idea if the app store would approve something like that.

I'd like to understand more about the store login problem, can you drop me a detailed explanation of what's not working well there, and I can try to figure out who to relay that to? If it's not by design for some reason, then it's possible that it may be fixed in a future software update.

I know entering lots of text from the virtual keyboard is kind of a pain, but you can connect a USB keyboard to it, which at least makes it a little easier.

**Comment by vaughnad** [comment] 2015-06-12 23:53
Hi Eric

My problemas is basically that I loged in using Facebook.
Now I can't create an account with my email.
If go to the lgapp site in my computer it says that my email is is already created but if I go to forget my password it says it does not exists.
And the site do note have an option to login using facebook.
So my account is inaccessible using the site.
And the TV never remember my acc.
:/

**Comment by ericblade-owo** [comment] 2015-06-13 00:00
So, the "Login with Facebook" option in the store login on TV is not sufficient, it requires you to use a different email?  Or is there not a Login with Facebook option?  Or you login with Facebook, and it still tells you you need to login?  (sorry for my confusion, I'm just not following exactly what happens, so I want to make sure I'm clear, before I try to figure out who I need to tell what :-) )

**Comment by vaughnad** [comment] 2015-06-13 00:11
The Facebook login works on the TV but it does not remember the user so you have to login every single time.

In the site the Facebook login is inexistent.

Since my email is the same as Facebook's I am unable to create an account using it, and since there is no Facebook login in the site I am unable to create an password for my account so I can use the common login form

**Comment by ericblade-owo** [comment] 2015-06-13 00:46
ok, so basically you have to re-enter your facebook information every time?  I'll try to see if I can locate someone to tell me if this is intentional, or if theres a technical reason for it, or what.  I can't guarantee if/when I would have an answer, and even if it were to be changed, i can't make any guesses as to when/if a software update would be available :|  (i'm just an engineer)

**Comment by vaughnad** [comment] 2015-06-13 01:01
Thanks for the help Eric ^^

**Closed as completed** 2015-07-01 08:37 UTC
